export const skillsContent = [
	{ name: "HTML / CSS" },
	{ name: "Electron" },
	{ name: "Python" },
	{ name: "NumPy" },
	{ name: "PyTorch" },
	{ name: "C / LLVM" },
	{ name: "JavaScript" },
	{ name: "TypeScript" },
	{ name: "Node.js" },
	{ name: "React" },
	{ name: "Next.js" },
	{ name: "Express.js" },
	{ name: "MongoDB" },
	{ name: "SQL" },
	{ name: "Wolfram Language" },
	{ name: "Postman" },
	{ name: "Java / C#" },
	{ name: "Android Studio" },
	{ name: "Git / GitHub" },
	{ name: "Linux" },
	{ name: "Figma" },
];
