export const skillsContent = [
	{ name: "Python" },
	{ name: "NumPy" },
	{ name: "C / GCC" },
	{ name: "Java" },
	{ name: "Android Studio" },
	{ name: "JavaScript" },
	{ name: "Node.js" },
	{ name: "Express.js" },
	{ name: "MongoDB" },
	{ name: "SQL" },
	{ name: "Postman" },
	{ name: "HTML / CSS" },
	{ name: "React" },
	{ name: "Next.js" },
	{ name: "Electron" },
	{ name: "Unity" },
	{ name: "C#" },
	{ name: "Git / GitHub" },
	{ name: "Figma" },
];
